pipeline {
    agent {
        label 'AGENT-1'
    }
    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    // environment{
    //     DEBUG='true'
    // }

    parameters{
        choice(name: 'ACTION', choices: ['Apply','Destroy'], description: 'Select Action')
    }

    stages{
        stage("Init and plan"){
            steps{
                withAWS(region: 'us-east-1', credentials: 'aws-creds'){
                    sh """
                    cd 00-vpc
                    terraform init -reconfigure
                    terraform plan -out=tfplan

                    """
                }   
            }
        }
        stage("Apply or Destroy"){
            steps{
                input {
                    message "Should we continue?"
                    ok "Yes, we should."
                }
                    withAWS(region: 'us-east-1', credentials: 'aws-creds'){
                        sh """
                        cd 00-vpc
                        if [${params.ACTION} == 'Apply']
                        then
                            terraform apply -auto-approve tfplan
                        elif [${params.ACTION} == 'Destroy'] 
                        then
                            terraform destroy -auto-approve
                        fi
                        """
                    }   
            }
        }
    }
    post{
        always{
            echo "This section will run always"
            deleteDir()
        }
        success{
            echo "This section will run when job got success"
        }
        failure{
            echo "This section will run when job got failure"
        }
    }
}